### ISSUE TITLE
Battleship - Create components and routes

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#1]
### **Task DoD**
- [x] Create every component needed for the app.
- [x] Link each component with an URL using routes.
- [x] Unit tests and coverage.
- [x] Linters.
