### ISSUE TITLE
Battleship - Implement Game Board Component

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#11]
### **Task DoD**
- [x] Define the table that will be the game board.
- [x] Include cells names.
- [x] Create a Service to generate a random initial distribution of the fleet.
- [x] Handle behaviour of user clicks on the board.
- [x] Add turn counter and link it to user actions.
- [x] Add accuracy counter and link it to user actions.
- [x] Add Save Game button and mock it's behaviour. Route to Main Menu Component.
- [x] Implement Final Results Component as a child of Game Board Component.
- [x] Implement Start and End game time.
- [x] Implement conditionally the Multiplayer layout.
- [x] Linters.
