### ISSUE TITLE
Battleship - Set up Node server

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#19]
### **Task DoD**
- [x] Create backend directory.
- [x] Install hapi and babel packages.
- [x] Setup Babel.
- [x] Write server's first code.
- [x] Install Postman.
- [x] Create routes directory with fake data and initial endpoints.
- [x] Set up automatic server restart.
- [x] Include error handling with Boom.
- [x] Linters.
