### ISSUE TITLE
Battleship -  Setup app style and background

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#2]
### **Task DoD**
- [x] Look for and download a suitable image for the app background, with high resolution and quality.
- [x] Insert image as background image and blur it al little.
- [x] Select and import a styles library into the project.
- [x] Create game console background with opacity.
- [x] Unit tests and coverage.
- [x] Linters.
