### ISSUE TITLE
Battleship - Set up a database with MySql and needed endpoints

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#21]
### **Task DoD**
- [x] Download MySql and MySql Workbench.
- [x] Create and configure a database.
- [x]  Connect Node server to the database.
- [x] Create endpoint to get Saved games.
- [x] Create endpoint to get Played games.
- [x] Create endpoint to register Saved games.
- [x] Create endpoint to register played games.
- [x] Create endpoint to get ship positions and clicked cell ids of the selected game for the current user on Load Game.
- [x] Create enpoint to register multiplayer code and check for code matches to join multiplayer room. Include endpoint for deleting codes.
- [x] Create endpoints to update saved games, clicked cell ids and ship positions
- [x] Linters.
