### ISSUE TITLE
Battleship - Communicate App with the server

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#24]
### **Task DoD**
- [x] Set up frontend to begin conection with the server.
- [x] Connect user's Saved and Played games.
- [x] Connect game saves.
- [x] Connect new Played game.
- [x] Connect game loads.
- [x] Create Delete Saved and Played games endpoints and connect them with the app.
- [ ] Connect multiplayer code generation.
- [ ] Add library to listen to database events.
- [ ] Connect multiplayer code check.
- [ ] Connect multiplayer code deletion.
- [ ] Linters.
