### ISSUE TITLE
Battleship - Add Firebase authentication to the app

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#26]
### **Task DoD**
- [x] Set up Firebase account.
- [x] Add Firebase to Angular.
- [x] Add Firebase to hapi.
- [x] Allow Sign in and out. Create Login and Logout buttons.
- [ ] Get user ID from Firebase.
- [ ] Linters
