### ISSUE TITLE
Battleship - Implement Main Menu Component

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#7]
### **Task DoD**
- [x] Set layout and styles.
- [x] Route each menu option with their components.
- [x] Unit tests and coverage.
- [x] Linters.
