### ISSUE TITLE
Battleship - Implement Difficulty Component

### ISSUE THREAD

**Issue by rodrafer** [rodrafer/battleship#9]
### **Task DoD**
- [x] Set layout and styles.
- [x] Include Back button.
- [x] Include Loading screen.
- [x] Unit tests and coverage.
- [x] Linters.
